
const playerNames = {
    Australia: [
      "Travis Head",
      "David Warner",
      "Steven Smith",
      "Glenn Maxwell",
      "Alex Carey",
      "Marcus Stoinos",
      "Marnus Labuschagne",
      "Pat Cummins",
      "Mitchell Starc",
      "Josh Hazlewood",
      "Adam Zampa",
    ],
    New_Zealand: [
      "Devon Conway",
      "Rachin Ravindra",
      "Kane Williamson",
      "Daryl Mitchell",
      "Glenn Phillips",
      "Tom Latham",
      "Mitchell Santner",
      "Ish Sodhi",
      "Trent Boult",
      "Tim Southee",
      "Henry Nicholls",
    ],
    India: [
      "Rohit Sharma",
      "Shikhar Dhawan",
      "Virat Kohli",
      "K. L. Rahul",
      "M.S Dhoni",
      "Hardik Pandya",
      "Ravindra Jadeja",
      "Akshar Patel",
      "Mohammed Shami",
      "Jasprit Bumrah",
      "Kuldeep Yadav",
    ],
    England: [
      "Jonny Baristow",
      "Jason Roy",
      "Joe Root",
      "Moien Ali",
      "Jos Buttler",
      "Ben Stokes",
      "Jofra Archer",
      "Sam Curran",
      "Chris Woakes",
      "Adil Rashid",
      "Mark Wood",
    ],
  };

export default playerNames
