
const playerNames = {
    Australia: [
      "Aaron Finch",
      "David Warner",
      "Steven Smith",
      "Glenn Maxwell",
      "Mattew Wade",
      "Marcus Stoinos",
      "Marnus Labuschagne",
      "Pat Cummins",
      "Mitchell Starc",
      "Kane Richardson",
      "Adam Zampa",
    ],
    New_Zealand: [
      "Henry Nicholls",
      "Martin Guptill",
      "Kane Williamson",
      "Ross Taylor",
      "James Neesham",
      "Colin de Grandhomme",
      "Tom Latham",
      "Mitchell Santner",
      "Trent Boult",
      "Tim Southee",
      "Lockie Ferguson",
    ],
    India: [
      "Rohit Sharma",
      "Shikhar Dhawan",
      "Virat Kohli",
      "K. L. Rahul",
      "M.S Dhoni",
      "Hardik Pandya",
      "Ravindra Jadeja",
      "Yuzvendra Chahal",
      "Mohammed Shami",
      "Jasprit Bumrah",
      "Kuldeep Yadav",
    ],
    England: [
      "Jonny Baristow",
      "Jason Roy",
      "Joe Root",
      "Eoin Morgan",
      "Jos Buttler",
      "Ben Stokes",
      "Jofra Archer",
      "Sam Curran",
      "Chris Woakes",
      "Adil Rashid",
      "Liam Plunkett",
    ],
  };

export default playerNames